baseURL = "https://pyhrr0.github.io/"
languageCode = "en-us"
title = ""
theme = "anatole"

[params]
title = "Pyhrr0"
author = "pyhrr0"
description = "Yet another inquisitive creature."
profilePicture = "images/logo.jpg"
contentRatio = 0.7
contactFormAction = "https://getform.io/f/d4cb0a53-03f7-4b02-9997-5e94ab89fac9"
mainSections = []

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/pyhrr0"

[[params.socialIcons]]
icon = "fab fa-gitlab"
title = "Gitlab"
url = "https://gitlab.com/pyhrr0"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://linkedin.com/in/pyhrr0"

[menu]
  [[menu.main]]
  name = "Home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  url = "/posts"

  [[menu.main]]
  name = "Resume"
  weight = 300
  url = "/resume"

  [[menu.main]]
  name = "Contact"
  weight = 400
  url = "/contact"
